Java/HelloWorld.java
python/HelloWorld.py

I have added the hello world programs for java and python

Hello World for python and java

---

contribute.md

I created the contribute.md file

created a contribute.md file

---

Javascript/Helloworld.js
Php/index.php

#1 
Added Php Hello_world code

Php hello world

---

Javascript/Helloworld.js

Javascript added

---

Haskell/hello_world.hs

This program is the famous (or infamous) "Hello World!" implemented in the functional programming language: Haskell.

Add Hello World program in Haskell

---

C++/coin_change.cpp

Add dynamic programming alg (coin change problem algorithm)

Add coin change alg

---

Java/TOANDFRO

https://www.spoj.com/problems/TOANDFRO/ problem link

created TOANDFRO

---

C++/bubble_sort.cpp

bubble_sort 

---

C++/mergesort.cpp

Commit by SarthakAgarwal147

---

C++/quicksort.cpp
C++/selectionsort.cpp

Contribution by SarthakAgarwal147

---

python/gcd.py

Added a program to find GCD of two numbers.

GCD of two numbers

---

Bash/Guess_A_Number/Guess.sh
Bash/Guess_A_Number/README.md

Added a number guessing game to the Bash folder. The game is contained within its own folder titled Guess_A_Number and contains the script; as well as, a README.md that explains how to use the script.

Added number guessing game to Bash folder

---

C++/tables.cpp

Added a tables program c++

---

neg.java

Colored image to Negative image conversion

colored img to negative

---

Groovy/HelloWorld.groovy

Added Hello World as script Groovy

Added Hello World as script Groovy

---

Dart/binary_search_tree.dart

Added a simple dart BST

---

C/recursion_factorial.c

To calculate factorial using recursion

recursion_factorial.c

---

C++/knapsack.cpp

Added the knapsack program to the C++ folder.
Happy Coding! :)

Added knapsack.cpp

---

.idea/.gitignore
.idea/Hacktoberfest2019.iml
.idea/modules.xml
.idea/vcs.xml
C++/mergesort.cpp
C/helloworld.c
Javascript/Helloworld.js
Kotlin/CustomDelegate.kt
Kotlin/Destructuring.kt

- Add some examples of destructuring declaration with Pair, Triple and Data Classes.

Add destructuring declaration and custom delegate with Kotlin

---

CONTRIBUTING.md

this java programs can be usefull for some experienced or fresher java dev .

java-permutation-problem (medium)
